name: Build Godot 4.7.1 Template

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

    # Исходники Godot
    - name: Checkout Godot source
      uses: actions/checkout@v4
      with:
        repository: godotengine/godot
        ref: 4.7.1-stable
        path: godot-src


    # Твой репозиторий с custom.py
    - name: Checkout custom files
      uses: actions/checkout@v4
      with:
        path: custom-template


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"


    - name: Install SCons
      run: pip install scons


    # Кладем custom.py в исходники Godot
    - name: Copy custom.py
      shell: cmd
      run: |
        copy custom-template\custom.py godot-src\custom.py


    # Сборка
    - name: Build Windows template
      working-directory: godot-src
      run: |
        scons platform=windows target=template_release production=yes lto=yes d3d12=no accesskit=no vulkan=no

    # Забираем результат
    - name: Upload template
      uses: actions/upload-artifact@v4
      with:
        name: godot-4.7.1-windows-template
        path: godot-src/bin/godot.windows.template_release.x86_64.exe
